### ISSUE TITLE
Acronyms and Glossaries

### ISSUE THREAD

**Issue by joaomlourenco** [joaomlourenco/unlthesis#21]
Find a good (and elegant) solution for dealing with acronyms and glossaries.

**Comment by bcandeias** [comment]
Actually, I have an elegant way...  by adding `acronym` to 

```latex
\usepackage[nonumberlist,translate=babel,acronym]{glossaries}
```

The package generates a new list, thus separating glossaries from acronyms. Is this what you're looking for? I can create a topic in the Wiki, or include a comprehensive example in Chapter 2. Whichever you prefer.

**Comment by joaomlourenco** [comment]
Suggestions from brandies applied in version 3.0.6.
