### ISSUE TITLE
IMS template

### ISSUE THREAD

**Issue by HelenaBaptista** [joaomlourenco/unlthesis#29]
Hi,

I just download the thesis template and was going to start, but when I tired to use: school=unl/ims, I got several error messages and the pdf was not showing the logo. 
Is IMS not yet added completely?

Thank you

**Comment by joaomlourenco** [comment]
Hi,

Indeed, the support for NOVA-IMS is not at 100%.   However, you should be able to process the template without errors.  (see attached image as an example).

Are you sure you are using "pdflatex" to process your document (and not "latex")?  I would guess that is your problem.  If you are using TexShop or similar, check the preferences and be sure that you are really using pdflatex.

Additionally, I kindly ask you to ask for support tin the [google group](https://groups.google.com/forum/#!forum/unlthesis)  and not here. Thank you.  

João Lourenço

[ims-cover.pdf](https://github.com/joaomlourenco/unlthesis/files/41143/ims-cover.pdf)

**Comment by HelenaBaptista** [comment]
João, thank you for the help.
If the NOVA_IMS is still not at 100% should I wait or can I start working?
Will I lose any work?
In fact your pdf is exactly equal to the one that I got, but I was missing
the logo... that is why I tought it was not OK.
I am using TeXShop and in preferences I only have the option Pdftex, is
that the one that you mean?

I will use the google group as of now, apologies for that.

Thank you!



2015-11-22 20:38 GMT+00:00 João Lourenço <notifications@github.com>:

> Hi,
>
> Indeed, the support for NOVA-IMS is not at 100%. However, you should be
> able to process the template without errors. (see attached image as an
> example).
>
> Are you sure you are using "pdflatex" to process your document (and not
> "latex")? I would guess that is your problem. If you are using TexShop or
> similar, check the preferences and be sure that you are really using
> pdflatex.
>
> Additionally, I kindly ask you to ask for support tin the google group
> <https://groups.google.com/forum/#!forum/unlthesis> and not here. Thank
> you.
>
> João Lourenço
>
> ims-cover.pdf
> <https://github.com/joaomlourenco/unlthesis/files/41143/ims-cover.pdf>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joaomlourenco/unlthesis/issues/29#issuecomment-158796622>
> .
>



-- 
Helena Baptista
Tel: 91 545 38 15

**Comment by joaomlourenco** [comment]
Helena,

You may start working with the current version of the template and you **will not** lose any work.

By the end of December the support for NOVA-IMS will be concluded.  Then you may contact me and I'll provide you with instructions on how to "upgrade" to the newer version.

If you still have errors/warnings concerning images, please move the discussion from here to the [unlthesis google group](https://groups.google.com/forum/#!forum/unlthesis) (https://groups.google.com/forum/#!forum/unlthesis) and post there a request for help.  Please include your "template.log" file as an attachment.

João L.

**Comment by HelenaBaptista** [comment]
Thank you, will do

Enviado do meu iPhone

No dia 22/11/2015, às 23:05, João Lourenço <notifications@github.com> escreveu:

**Comment by HelenaBaptista** [comment]
Olá João,

Feliz Ano Novo.
Estou de volta ao assunto da versão para a NOVA IMS. Já tem novidades?

Obrigada, cumprimentos,

2015-11-22 23:07 GMT+00:00 Helena Baptista <gema272005@gmail.com>:

> Thank you, will do
>
> Enviado do meu iPhone
>
> No dia 22/11/2015, às 23:05, João Lourenço <notifications@github.com>
> escreveu:
>
> Helena,
>
> You may start working with the current version of the template and you *will
> not* lose any work.
>
> By the end of December the support for NOVA-IMS will be concluded. Then
> you may contact me and I'll provide you with instructions on how to
> "upgrade" to the newer version.
>
> If you still have errors/warnings concerning images, please move the
> discussion from here to the unlthesis google group
> <https://groups.google.com/forum/#!forum/unlthesis> (
> https://groups.google.com/forum/#!forum/unlthesis) and post there a
> request for help. Please include your "template.log" file as an attachment.
>
> João L.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joaomlourenco/unlthesis/issues/29#issuecomment-158817006>
> .
>
>


-- 
Helena Baptista
Tel: 91 545 38 15
