### ISSUE TITLE
New Institutions

### ISSUE THREAD

**Issue by HelenaBaptista** [joaomlourenco/unlthesis#33]
Hello,

Is there any plan to include Faculdade de Ciências, Universidade de Lisboa?

Thank you

**Comment by joaomlourenco** [comment]
If there is someone interested…  Why not?!  :)
Send me the FCUL regulations for the cover, margins, thesis organisation, etc, and I'll take care of it.

**Comment by HelenaBaptista** [comment]
As I have been told (is for a colleague of us that is doing the PhD in FCUL) it can be equal to ours in the Nova University, just has to have the FCUL logo.
I will ask my colleague to give it to me and I will send it.
Thank you :)

**Comment by HelenaBaptista** [comment]
Hi João,

Attached is the cover page for FCUL.
Ana (coppied in this email) is the PhD student that needs it.
She has been told that the template can be whatever, only the cover needs
to be this one.

Thank you so much for your help.

Ana & Helena

2016-02-06 21:20 GMT+00:00 João Lourenço <notifications@github.com>:

> If there is someone interested… Why not?! :)
> Send me the FCUL regulations for the cover, margins, thesis organisation,
> etc, and I'll take care of it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joaomlourenco/unlthesis/issues/33#issuecomment-180866935>
> .
>



-- 
Helena Baptista
Tel: 91 545 38 15

**Comment by HelenaBaptista** [comment]
and the document :)

2016-02-27 15:32 GMT+00:00 Helena Baptista <gema272005@gmail.com>:

> Hi João,
>
> Attached is the cover page for FCUL.
> Ana (coppied in this email) is the PhD student that needs it.
> She has been told that the template can be whatever, only the cover needs
> to be this one.
>
> Thank you so much for your help.
>
> Ana & Helena
>
> 2016-02-06 21:20 GMT+00:00 João Lourenço <notifications@github.com>:
>
>> If there is someone interested… Why not?! :)
>> Send me the FCUL regulations for the cover, margins, thesis organisation,
>> etc, and I'll take care of it.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/joaomlourenco/unlthesis/issues/33#issuecomment-180866935>
>> .
>>
>
>
>
> --
> Helena Baptista
> Tel: 91 545 38 15
>



-- 
Helena Baptista
Tel: 91 545 38 15

**Comment by joaomlourenco** [comment]
Still no document.  Send it by email directly to me please.  :)

**Comment by joaomlourenco** [comment]
FCUL is supported now.
