### ISSUE TITLE
NOVA-IMS spine

### ISSUE THREAD

**Issue by tomasjmonteiro** [joaomlourenco/unlthesis#35]
there is a need to replace the **\thelastsheet+19** (line 23) by **\thelastsheet** as this command gives the total number of pages, including the frontmatter, as is on the spine.clo on the unlthesis-files folder.

there is a problem with the long title names (140char) on this spine, as they are written over the green boxes when they run out of space, maybe solved by using a smaller font size whenever the size of the title box is greater than the white space, as when the author title is below the title the box cannot have linebreaks

**Comment by joaomlourenco** [comment]
NOVA IMS spine is working now.
