### ISSUE TITLE
Compilation problems

### ISSUE THREAD

**Issue by outbound-pt** [joaomlourenco/unlthesis#40]
Greetings,

I always get the following compilation error as soon as I try to compile the template:
![screen shot 2016-06-29 at 14 11 34](https://cloud.githubusercontent.com/assets/10950527/16453317/5356e794-3e04-11e6-8502-dfee724bdac7.png)

I'm using TeXMaker on Mac OS X.

Best regards,

**Comment by bcandeias** [comment]
Hi, 

This is odd. It must have to do with your setup. I also use Mac OSX with MacTeX (the LaTeX distribution) and I can compile the template “as is”.

Can you please open the application “TeX Live Utility” and confirm that the packages are all up to date?

Thanks,
Bruno

**Comment by outbound-pt** [comment]
It crashes... *sigh*

It finally worked but said it couldn't find a valid update server.

I'm downloading the latest MacTeX package file.

I'll try installing that and see if the utility runs or the problem fixes itself.

I'll let you know.

**Comment by bcandeias** [comment]
Sometimes the TeX Live Utility itself needs to be updated. That might be a possible cause for the crash.

Nevertheless, installing a fresh version of MacTeX might be a good option. I think they have a script to uninstall a previous version. Be sure to run it before installing the new version, so they don’t get mixed up.

Keep me posted.

**Comment by outbound-pt** [comment]
So, several things.

TL,DR: It's working.

Basically I had a very old distribution installed (2012). Even after installing the newest package and updating libraries I still had the error. I then spotted a reference on problems with el Capitan:

https://tug.org/mactex/UpdatingForElCapitan.pdf

All seems well now.

Many thanks!

**Comment by bcandeias** [comment]
Hi, great to hear!

I still use Yosemite, so El-Capitan-specific issues are oblivious to me. I’m glad you could sort it out.

Almost all the times, errors concerning package incompatibilities and such occur to missing updates. Before updating the code in the repository, we make sure that everything is working correctly. So in doubt, updating all the packages, LaTeX version and template version is enough to solve such problems.

Good luck with your work.
