### ISSUE TITLE
Package biblatex Warning: Using fall-back BibTeX(8) backend

### ISSUE THREAD

**Issue by luismsgomes** [joaomlourenco/unlthesis#41]
I couldn't make this warning go away:

Package biblatex Warning: Using fall-back BibTeX(8) backend:
(biblatex)                functionality may be reduced/unavailable.

I tried setting backend=biber, backend=bibtex, and backend=bibtex8. Either in template.tex documentclass or directly in unlthesis-files/packages.clo, to no avail.

How to reproduce:

pdflatex template.tex

By the way, thanks for unlthesis : -).

**Comment by joaomlourenco** [comment]
This issue was moved to joaomlourenco/novathesis#6
