### ISSUE TITLE
Print Spine Bug

### ISSUE THREAD

**Issue by bernymac** [joaomlourenco/unlthesis#43]
When the flag to print the thesis spine is set to true, a compilation error occurs. This has been tested on both a real thesis and with a barebones download-and-compile version of the project.
Compilation error on barebones project:

Processing: Chapters/appendix1.tex

Including: unlthesis-files/Schools/unl/fct/Images/logoUNL.pdf
Latex Error: ./template.tex:271 Missing number, treated as zero.

Latex Error: ./template.tex:271 Illegal unit of measure (pt inserted).

LaTeX Font Warning: Some font shapes were not available, defaults substituted.

Output written on template.pdf (107 pages, 560546 bytes).

Complete transcript is in template.log

Command pdflatex -interaction=nonstopmode -file-line-error-style -synctex=1 exited with status 1

Found 2 errors, and 4 warnings in 1 run

**Comment by bernymac** [comment]
Solved. Update TeX distribution from TeXLive-2015 to TeXLive-2016.

**Comment by bcandeias** [comment]
Thanks for sharing, glad you solved it. I didn't have time to look at it!

**Comment by bernymac** [comment]
By the way, there is a known bug with TeXLive-2016 and bibtex. Supposedly it has to do with big urls. When updating I had to add the following lines after the \addbibfile{...} instruction.

\makeatletter
\def\blx@maxline{77}
\makeatother
