### ISSUE TITLE
FCT-UNL PhD for "graus em associação"

### ISSUE THREAD

**Issue by ruimcportela** [joaomlourenco/unlthesis#45]
Como falamos na aula de latex (prof João Lourenço), não existe template para a capa de doutoramento para graus em associação. Por isso venho pedir para fazer um template em latex (pdf em anexo - doc disponível no CLIP).
Obrigado,
Rui
[Formatação de capas de dissertações (graus em associação).doc.pdf](https://github.com/joaomlourenco/unlthesis/files/556090/Formatacao.de.capas.de.dissertacoes.graus.em.associacao.doc.pdf)

**Comment by joaomlourenco** [comment]
Working on it…

**Comment by joaomlourenco** [comment]
This issue was moved to joaomlourenco/novathesis#4
